/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 public/models/fighter/fighter.glb
Author: JoseDiaz (https://sketchfab.com/JoseDiaz)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/arcade-fighter-1-f95c4ee709ad4ab9a5ec4b96cc960437
Title: Arcade Fighter 1
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export default function Figher(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/models/Fighter/fighter.glb')
  const { mixer, actions } = useAnimations(animations, group)

  useEffect(() => {
    console.log(actions);
    mixer.timeScale = .2;
    actions['Fighter1_Fight_Stance'].play()
  }, [])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fbx_mergefbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="Object_6" rotation={[-Math.PI / 2, 0, 0]} />
                  <group name="Fighter1_Mesh" rotation={[-Math.PI / 2, 0, 0]} />
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry}  skeleton={nodes.Object_7.skeleton} >
                    {/* material={materials.Fighter1} */}
                    <meshStandardMaterial 
                      // color={0x708090}
                      metalness={1}
                      roughness={0.28}
                      />
                  </skinnedMesh>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/fighter.glb')
